### ISSUE TITLE
Copying the world folder?

### ISSUE THREAD

**Issue by WildKarrade** [dodexahedron/SE-Community-Mod-API#10] opened 2015-03-13 23:38 UTC
Is there any specific reason SEServerExtender would be doing this? I don't recall Tyrsis's doing this and don't think it's normal. It seems to be duplicating the save and saving to the duplicated folder with random numbers at the end for some reason when saving, instead of actually saving normally.

http://aero-tech.me/sharex/uploads/h8L84789.png

**Comment by dodexahedron** [comment] 2015-03-14 02:49
I haven't touched the logic around game saves.
Are you sure you're loading up the correct instance?  That can cause the behavior you're mentioning.

**Comment by WildKarrade** [comment] 2015-03-14 15:18
positive, checked it multiple times. The only thing I can think of that would cause this is the essentials backup settings maybe not working(haven't tested this).

**Comment by dodexahedron** [comment] 2015-03-14 17:15
Please pastebin a copy of your configuration file.
I can't duplicate this behavior.

**Comment by WildKarrade** [comment] 2015-03-14 17:42
Here you go http://pastebin.com/ztFXMydt 

Actually i'm thinking it might actually be related to procedural mode creating those folders for sectors and SEServerExtender doesn't load them correctly or something.

**Comment by dodexahedron** [comment] 2015-03-17 05:37
Closing as duplicate of/in favor of https://github.com/Tyrsis/SE-Community-Mod-API/issues/61

**Closed as completed by dodexahedron** 2015-03-17 05:37 UTC
